local view_cardType=
{
	name="view_cardType",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="view_type",type=0,typeName="View",time=0,x=0,y=0,width=120,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
		{
			name="img_bg_1",type=1,typeName="Image",time=0,x=0,y=0,width=96,height=25,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="games/pokdeng/cardType/bg_1.png",gridLeft=20,gridRight=20,
			{
				name="tag_type",type=1,typeName="Image",time=0,x=0,y=0,width=89,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="games/pokdeng/cardType/tag_point.png",gridLeft=10
			},
			{
				name="tag_value",type=1,typeName="Image",time=0,x=28,y=0,width=24,height=28,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="games/pokdeng/cardType/0.png"
			}
		},
		{
			name="img_bg_2",type=1,typeName="Image",time=0,x=0,y=0,width=104,height=46,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="games/pokdeng/cardType/bg_2.png",
			{
				name="tag_type",type=1,typeName="Image",time=0,x=0,y=0,width=69,height=29,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="games/pokdeng/cardType/pokdeng_8.png"
			}
		},
		{
			name="img_bg_3",type=1,typeName="Image",time=0,x=0,y=0,width=130,height=35,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="games/pokdeng/cardType/bg_3.png",gridLeft=20,gridRight=20,
			{
				name="ear_1",type=1,typeName="Image",time=0,x=0,y=0,width=24,height=33,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="games/pokdeng/cardType/ear_1.png"
			},
			{
				name="ear_2",type=1,typeName="Image",time=0,x=0,y=0,width=24,height=33,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="games/pokdeng/cardType/ear_2.png"
			},
			{
				name="tag_type",type=1,typeName="Image",time=0,x=0,y=0,width=100,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="games/pokdeng/cardType/tag_straightFlush.png"
			}
		},
		{
			name="tag_times",type=1,typeName="Image",time=0,x=-54,y=0,width=54,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="games/pokdeng/cardType/x2.png"
		}
	}
}
return view_cardType;