local sysMsgItem=
{
	name="sysMsgItem",type=0,typeName="View",time=0,x=-55,y=0,width=610,height=93,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,
	{
		name="Image2",type=1,typeName="Image",time=0,x=0,y=0,width=610,height=93,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/message/item_bg.png",gridLeft=5,gridRight=5,gridTop=5,gridBottom=5,
		{
			name="Image3",type=1,typeName="Image",time=0,x=15,y=0,width=46,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="popu/message/email.png"
		},
		{
			name="view_content",type=0,typeName="View",time=0,x=70,y=0,width=380,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,
			{
				name="text_content",type=5,typeName="TextView",time=0,x=0,y=2,width=380,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignLeft,colorRed=46,colorGreen=82,colorBlue=160,colorA=1,string=[[MsgCont]]
			},
			{
				name="img_rewardBg",type=1,typeName="Image",time=0,x=0,y=45,width=320,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="popu/message/reward_bg.png",gridLeft=25,gridRight=25,
				{
					name="text_rewardName",type=4,typeName="Text",time=0,x=5,y=0,width=12.85,height=28,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=204,colorBlue=25,colorA=1
				},
				{
					name="img_chip",type=1,typeName="Image",time=0,x=0,y=0,width=28,height=28,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="popu/message/icon_chip.png"
				},
				{
					name="text_rewardNum",type=4,typeName="Text",time=0,x=0,y=0,width=12.85,height=28,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=26,textAlign=kAlignLeft,colorRed=255,colorGreen=204,colorBlue=25,colorA=1
				}
			}
		},
		{
			name="btn_itemEvt",type=1,typeName="Button",time=0,x=0,y=0,width=610,height=93,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="ui/blank.png"
		},
		{
			name="btn_confirm",type=1,typeName="Button",time=0,x=10,y=0,width=130,height=54,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="popu/btn_blue.png",
			{
				name="text_btn",type=4,typeName="Text",time=0,x=0,y=0,width=85,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=32,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,colorA=1,string=[[Action]]
			}
		}
	}
}
return sysMsgItem;