--掉金币动画
coin_pin_map = {
	
	["1.png"]={ 
		file="/animation/dropCoins/coin_pin.png",
		x=69,y=136,
		width=65,height=65
	},
	["2.png"]={ 
		file="/animation/dropCoins/coin_pin.png",
		x=69,y=69,
		width=65,height=65
	},
	["3.png"]={ 
		file="/animation/dropCoins/coin_pin.png",
		x=136,y=2,
		width=65,height=65
	},
	["4.png"]={ 
		file="/animation/dropCoins/coin_pin.png",
		x=69,y=2,
		width=65,height=65
	},
	["5.png"]={ 
		file="/animation/dropCoins/coin_pin.png",
		x=2,y=136,
		width=65,height=65
	},
	["6.png"]={ 
		file="/animation/dropCoins/coin_pin.png",
		x=2,y=69,
		width=65,height=65
	},
	["7.png"]={ 
		file="/animation/dropCoins/coin_pin.png",
		x=2,y=2,
		width=65,height=65
	},
}