local menuPopu=
{
	name="menuPopu",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="img_popuBg",type=1,typeName="Image",time=0,x=10,y=10,width=196,height=262,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="games/pokdeng/menu/bg.png",
		{
			name="btn_back",type=1,typeName="Button",time=0,x=6,y=7,width=182,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/blank.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20,
			{
				name="Image4",type=1,typeName="Image",time=0,x=15,y=0,width=50,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="games/pokdeng/menu/back.png"
			},
			{
				name="text",type=4,typeName="Text",time=0,x=80,y=0,width=100,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=30,textAlign=kAlignLeft,colorRed=246,colorGreen=219,colorBlue=182,string=[[Text]],colorA=1
			}
		},
		{
			name="btn_stand_up",type=1,typeName="Button",time=0,x=6,y=91,width=182,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/blank.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20,
			{
				name="Image4",type=1,typeName="Image",time=0,x=15,y=0,width=50,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="games/pokdeng/menu/stand_up.png"
			},
			{
				name="text",type=4,typeName="Text",time=0,x=80,y=0,width=100,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=30,textAlign=kAlignLeft,colorRed=246,colorGreen=219,colorBlue=182,string=[[Text]],colorA=1
			}
		},
		{
			name="btn_rule",type=1,typeName="Button",time=0,x=6,y=175,width=182,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/blank.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20,
			{
				name="Image4",type=1,typeName="Image",time=0,x=20,y=0,width=40,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="games/pokdeng/menu/rule.png"
			},
			{
				name="text",type=4,typeName="Text",time=0,x=80,y=0,width=100,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=30,textAlign=kAlignLeft,colorRed=246,colorGreen=219,colorBlue=182,string=[[Text]],colorA=1
			}
		},
		{
			name="Image13",type=1,typeName="Image",time=0,x=0,y=87,width=164,height=2,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="games/pokdeng/menu/line.png"
		},
		{
			name="Image14",type=1,typeName="Image",time=0,x=0,y=172,width=164,height=2,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="games/pokdeng/menu/line.png"
		}
	}
}
return menuPopu;