local friendAddCtrlView=
{
	name="friendAddCtrlView",type=0,typeName="View",time=0,x=0,y=0,width=626,height=660,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
	{
		name="View1",type=0,typeName="View",time=0,x=0,y=26,width=577,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,
		{
			name="Image5",type=1,typeName="Image",time=0,x=0,y=0,width=420,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="popu/friends/input_bg.png",gridLeft=32,gridRight=32,
			{
				name="et_id",type=6,typeName="EditText",time=0,x=30,y=0,width=360,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,colorA=1,fillTopLeftX=30,fillBottomRightX=30,fillTopLeftY=0,fillBottomRightY=0
			}
		},
		{
			name="btn_search",type=1,typeName="Button",time=0,x=0,y=0,width=146,height=72,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="common/btn_green_min.png",
			{
				name="Image16",type=1,typeName="Image",time=0,x=0,y=-5,width=82,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/text_search.png"
			}
		},
		{
			name="btn_cancel",type=1,typeName="Button",time=0,x=0,y=0,width=146,height=72,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="common/btn_blue_min.png",
			{
				name="Image16",type=1,typeName="Image",time=0,x=0,y=-5,width=82,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/friends/cancel.png"
			}
		}
	},
	{
		name="view_request",type=0,typeName="View",time=0,x=0,y=0,width=626,height=544,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fillTopLeftY=116,fillTopLeftX=0,fillBottomRightX=0,fillBottomRightY=0,
		{
			name="text_request",type=4,typeName="Text",time=0,x=20,y=10,width=100,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignTopLeft,colorRed=141,colorGreen=50,colorBlue=24,string=[[0]],colorA=1
		},
		{
			name="Image9",type=1,typeName="Image",time=0,x=0,y=60,width=624,height=4,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/friends/separate_lines.png"
		},
		{
			name="listview_request",type=0,typeName="ListView",time=0,x=0,y=0,width=626,height=454,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fillTopLeftY=80,fillTopLeftX=0,fillBottomRightX=0,fillBottomRightY=10
		},
		{
			name="view_request_empty",type=0,typeName="View",time=0,x=115,y=371,width=626,height=454,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fillBottomRightY=10,fillTopLeftX=0,fillBottomRightX=0,fillTopLeftY=80,
			{
				name="text_request_empty",type=5,typeName="TextView",time=0,x=0,y=0,width=350,height=250,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=22,textAlign=kAlignCenter,colorRed=141,colorGreen=50,colorBlue=24,string=[[TextView]],colorA=1
			}
		}
	},
	{
		name="view_result",type=0,typeName="View",time=0,x=216,y=429,width=626,height=544,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fillTopLeftY=116,fillTopLeftX=0,fillBottomRightX=0,fillBottomRightY=0,
		{
			name="Image12",type=1,typeName="Image",time=0,x=0,y=20,width=624,height=4,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/friends/separate_lines.png"
		},
		{
			name="listview_result",type=0,typeName="ListView",time=0,x=271,y=623,width=626,height=494,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fillBottomRightY=10,fillTopLeftX=0,fillBottomRightX=0,fillTopLeftY=40
		}
	}
}
return friendAddCtrlView;