local userInfoPopu=
{
	name="userInfoPopu",type=0,typeName="View",time=0,x=65,y=66,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,
	{
		name="bg_mainPanel",type=1,typeName="Image",time=0,x=0,y=0,width=720,height=1051,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/v210/bg_superBig.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20,
		{
			name="img_decBgTitle",type=1,typeName="Image",time=0,x=0,y=-496,width=527,height=74,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/v210/img_title_2.png",
			{
				name="img_dscTitle",type=1,typeName="Image",time=0,x=0,y=-2,width=178,height=49,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="language/thai/popu/usrInfo/usrInfo_dscTitle.png"
			}
		},
		{
			name="btn_close",type=1,typeName="Button",time=0,x=306,y=-499,width=113,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/v210/closebtn_ .png"
		},
		{
			name="bg_usrHeadBor",type=1,typeName="Image",time=0,x=65,y=72,width=216,height=213,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="popu/usrInfo/usrInfo_bgUsrHead.png",
			{
				name="img_usrHead",type=1,typeName="Image",time=0,x=12,y=-3,width=158,height=158,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="lobby/hall_avator_bg.png"
			},
			{
				name="btn_headAlert",type=1,typeName="Button",time=0,x=12,y=54,width=158,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/usrInfo/usrInfo_btnAlertHead.png",
				{
					name="txt_headAltert",type=4,typeName="Text",time=0,x=0,y=0,width=158,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Head Alert]],colorA=1
				}
			}
		},
		{
			name="btn_rewBox",type=1,typeName="Button",time=0,x=-288,y=-239,width=43,height=55,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/usrInfo/usrInfo_btnRewBox.png"
		},
		{
			name="txt_usrInfoID",type=4,typeName="Text",time=0,x=86,y=289,width=175,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=0,colorGreen=0,colorBlue=0,string=[[ID:Usr ID]],colorA=1
		},
		{
			name="ic_usrSex",type=1,typeName="Image",time=0,x=46,y=-415,width=41,height=41,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/usrInfo/usrInfo_icFemale.png"
		},
		{
			name="tv_usrName",type=5,typeName="TextView",time=0,x=167,y=-415,width=188,height=35,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=28,textAlign=kAlignCenter,colorRed=18,colorGreen=96,colorBlue=136,string=[[Usr Name]],colorA=1
		},
		{
			name="ic_nameAlertPen",type=1,typeName="Image",time=0,x=284,y=-415,width=34,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/usrInfo/usrInfo_icAlertPen.png"
		},
		{
			name="btn_nameAlert",type=1,typeName="Button",time=0,x=58,y=-415,width=278,height=48,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="common/blank.png"
		},
		{
			name="img_decUsrInfoDivLine",type=1,typeName="Image",time=0,x=164,y=-387,width=284,height=3,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/usrInfo/usrInfo_decUsrPepInfoDivLine.png"
		},
		{
			name="txt_usrLevel",type=4,typeName="Text",time=0,x=134,y=-360,width=218,height=29,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=25,textAlign=kAlignCenter,colorRed=150,colorGreen=60,colorBlue=30,string=[[LV.Usr Level]],colorA=1
		},
		{
			name="img_usrExpLayer",type=1,typeName="Image",time=0,x=385,y=-340,width=218,height=15,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="popu/usrInfo/usrInfo_prgLayerExp.png",
			{
				name="img_usrExpFiller",type=1,typeName="Image",time=0,x=3,y=0,width=5,height=16,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="popu/usrInfo/usrInfo_prgFillerExp.png"
			}
		},
		{
			name="btn_usrExpAbout",type=1,typeName="Button",time=0,x=282,y=-357,width=34,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/usrInfo/usrInfo_btnQExp.png"
		},
		{
			name="ic_currencyChip",type=1,typeName="Image",time=0,x=385,y=-288,width=47,height=49,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="popu/usrInfo/usrInfo_icChip.png"
		},
		{
			name="tv_usrChipNum",type=5,typeName="TextView",time=0,x=441,y=-288,width=185,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignLeft,colorRed=105,colorGreen=0,colorBlue=0,string=[[Usr Chip Num]],colorA=1
		},
		{
			name="btn_getCurrencyChip",type=1,typeName="Button",time=0,x=282,y=-288,width=34,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/usrInfo/usrInfo_btnAddCurrency.png"
		},
		{
			name="ic_currencyCash",type=1,typeName="Image",time=0,x=385,y=-227,width=42,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="popu/usrInfo/usrInfo_icCash.png"
		},
		{
			name="tv_usrCashNum",type=5,typeName="TextView",time=0,x=441,y=-227,width=185,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignLeft,colorRed=105,colorGreen=0,colorBlue=0,string=[[Usr Cash Num]],colorA=1
		},
		{
			name="btn_getCurrencyCash",type=1,typeName="Button",time=0,x=282,y=-227,width=34,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/usrInfo/usrInfo_btnAddCurrency.png"
		},
		{
			name="vb_usrGameInfoTab",type=0,typeName="View",time=0,x=0,y=-145,width=660,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
			{
				name="btn_tabIdx1",type=1,typeName="Button",time=0,x=0,y=0,width=330,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="common/blank.png",file2="common/blank.png",
				{
					name="img_tabBtnNor",type=1,typeName="Image",time=0,x=0,y=0,width=330,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="popu/usrInfo/usrInfo_btnTabIdx1_nor.png",
					{
						name="img_dscTxt",type=1,typeName="Image",time=0,x=0,y=0,width=166,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="language/thai/popu/usrInfo/usrInfo_dscTabIdx1_nor.png"
					}
				},
				{
					name="img_tabBtnSel",type=1,typeName="Image",time=0,x=0,y=0,width=330,height=70,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="popu/usrInfo/usrInfo_btnTabIdx1_sel.png",
					{
						name="img_dscTxt",type=1,typeName="Image",time=0,x=0,y=0,width=166,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="language/thai/popu/usrInfo/usrInfo_dscTabIdx1_sel.png"
					}
				}
			},
			{
				name="btn_tabIdx2",type=1,typeName="Button",time=0,x=1,y=0,width=330,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="common/blank.png",file2="common/blank.png",
				{
					name="img_tabBtnNor",type=1,typeName="Image",time=0,x=0,y=0,width=330,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="popu/usrInfo/usrInfo_btnTabIdx2_nor.png",
					{
						name="img_dscTxt",type=1,typeName="Image",time=0,x=0,y=0,width=166,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="language/thai/popu/usrInfo/usrInfo_dscTabIdx2_nor.png"
					}
				},
				{
					name="img_tabBtnSel",type=1,typeName="Image",time=0,x=0,y=0,width=330,height=70,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="popu/usrInfo/usrInfo_btnTabIdx2_sel.png",
					{
						name="img_dscTxt",type=1,typeName="Image",time=0,x=0,y=0,width=166,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="language/thai/popu/usrInfo/usrInfo_dscTabIdx2_sel.png"
					}
				}
			}
		},
		{
			name="vb_usrGameInfo",type=0,typeName="View",time=0,x=0,y=42,width=660,height=590,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom
		},
		{
			name="vb_usrPropInfo",type=0,typeName="View",time=0,x=0,y=43,width=660,height=590,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,
			{
				name="txt_noPropHint",type=4,typeName="Text",time=0,x=0,y=0,width=370,height=48,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=32,textAlign=kAlignCenter,colorRed=255,colorGreen=0,colorBlue=0,string=[[No Prop Hint]],colorA=1
			}
		}
	}
}
return userInfoPopu;