local lobbyLayout=
{
	name="lobbyLayout",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,
	{
		name="lobbyBg",type=1,typeName="Image",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,file="lobby/hall_bg.png"
	},
	{
		name="topView",type=0,typeName="View",time=0,x=0,y=0,width=720,height=107,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
		{
			name="topbarBg",type=1,typeName="Image",time=0,x=0,y=0,width=720,height=107,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="lobby/hall_topbar_bg.png"
		},
		{
			name="infoView",type=0,typeName="View",time=0,x=10,y=10,width=200,height=76,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="img_headBg",type=1,typeName="Image",time=0,x=0,y=0,width=71,height=71,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="lobby/hall_avator_bg.png",
				{
					name="headBtn",type=1,typeName="Button",time=0,x=0,y=0,width=71,height=71,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="ui/blank.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20
				}
			},
			{
				name="nickTxt",type=4,typeName="Text",time=0,x=76,y=0,width=120,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignTopLeft,colorRed=8,colorGreen=106,colorBlue=151,string=[[好多鱼]],colorA=1
			},
			{
				name="levelTxt",type=4,typeName="Text",time=0,x=77,y=16,width=50,height=31.65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomLeft,fontSize=26,textAlign=kAlignBottomLeft,colorRed=8,colorGreen=106,colorBlue=151,string=[[Lv.7]],colorA=1
			},
			{
				name="iconVip",type=1,typeName="Image",time=0,x=120,y=18,width=43,height=19,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomLeft,file="lobby/icon_vip_1.png"
			},
			{
				name="img_exp_progressBg",type=1,typeName="Image",time=0,x=74,y=27,width=87,height=6,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="lobby/hall_exp_progress_bg.png",
				{
					name="img_exp_progressFg",type=1,typeName="Image",time=0,x=0,y=0,width=8,height=6,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="lobby/hall_exp_progress_fg.png"
				}
			},
			{
				name="btn_head",type=1,typeName="Button",time=0,x=-10,y=0,width=180,height=90,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/blank.png"
			}
		},
		{
			name="topCashView",type=0,typeName="View",time=0,x=14,y=25,width=206,height=59,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,
			{
				name="Image34",type=1,typeName="Image",time=0,x=31,y=-3,width=169,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="lobby/hall_chip_bg.png"
			},
			{
				name="Image35",type=1,typeName="Image",time=0,x=0,y=0,width=70,height=68,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="lobby/hall_chip.png"
			},
			{
				name="addCashBtn",type=1,typeName="Button",time=0,x=0,y=0,width=70,height=68,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="lobby/hall_chip.png"
			},
			{
				name="cashNumTxt",type=4,typeName="Text",time=0,x=20,y=-4,width=104,height=41,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=28,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,colorA=1
			},
			{
				name="addCashBtn2",type=1,typeName="Button",time=0,x=0,y=-4,width=205,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/blank.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20
			}
		},
		{
			name="topChipView",type=0,typeName="View",time=0,x=229,y=25,width=265,height=59,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,
			{
				name="Image38",type=1,typeName="Image",time=0,x=30,y=-1,width=230,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="lobby/hall_chip_bg.png"
			},
			{
				name="Image39",type=1,typeName="Image",time=0,x=0,y=0,width=70,height=68,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="lobby/hall_cash.png"
			},
			{
				name="chipTxt",type=4,typeName="Text",time=0,x=25,y=-2,width=159,height=41,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=28,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,colorA=1
			},
			{
				name="addChipBtn",type=1,typeName="Button",time=0,x=0,y=0,width=70,height=68,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="lobby/hall_cash.png"
			},
			{
				name="addChipBtn2",type=1,typeName="Button",time=0,x=0,y=0,width=260,height=65,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/blank.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20
			}
		}
	},
	{
		name="middleView",type=0,typeName="View",time=0,x=0,y=0,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
		{
			name="mainGameView",type=0,typeName="View",time=0,x=-49,y=-250,width=100,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
		},
		{
			name="hotGameView",type=0,typeName="View",time=0,x=-234,y=206,width=100,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter
		},
		{
			name="recentGameView",type=0,typeName="View",time=0,x=0,y=206,width=100,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter
		},
		{
			name="moreGameView",type=0,typeName="View",time=0,x=234,y=206,width=100,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter
		}
	},
	{
		name="bottomView",type=0,typeName="View",time=0,x=0,y=0,width=720,height=128,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignBottom,
		{
			name="Image19",type=1,typeName="Image",time=0,x=0,y=-204,width=720,height=331,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="lobby/hall_bottombar_bg.png"
		},
		{
			name="inviteBtn",type=1,typeName="Button",time=0,x=1,y=149,width=87,height=106,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,file="lobby/hall_invite_btn.png"
		},
		{
			name="friendsBtn",type=1,typeName="Button",time=0,x=106,y=148,width=102,height=106,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,file="common/blank.png",
			{
				name="Image36",type=1,typeName="Image",time=0,x=0,y=0,width=87,height=106,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="lobby/hall_friends_btn.png"
			},
			{
				name="img_newTip",type=1,typeName="Image",time=0,x=50,y=-42,width=20,height=20,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/img_tipPoint.png"
			}
		},
		{
			name="feedbackBtn",type=1,typeName="Button",time=0,x=148,y=3,width=145,height=102,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/blank.png",
			{
				name="Image37",type=1,typeName="Image",time=0,x=0,y=2,width=84,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="lobby/feedback.png"
			}
		},
		{
			name="messageBtn",type=1,typeName="Button",time=0,x=-141,y=3,width=145,height=102,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/blank.png",
			{
				name="Image38",type=1,typeName="Image",time=0,x=0,y=6,width=84,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="lobby/hall_message_btn.png"
			},
			{
				name="img_newTip",type=1,typeName="Image",time=0,x=50,y=-42,width=20,height=20,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="common/img_tipPoint.png"
			}
		},
		{
			name="storeBtn",type=1,typeName="Button",time=0,x=0,y=0,width=145,height=149,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomLeft,file="common/blank.png",
			{
				name="Image39",type=1,typeName="Image",time=0,x=0,y=0,width=121,height=149,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="lobby/hall_store_btn.png"
			}
		},
		{
			name="moreBtn",type=1,typeName="Button",time=0,x=0,y=0,width=138,height=132,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,file="common/blank.png",
			{
				name="Image40",type=1,typeName="Image",time=0,x=0,y=-21,width=68,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="lobby/more.png"
			}
		},
		{
			name="welfareCenterBtn",type=1,typeName="Button",time=0,x=3,y=3,width=145,height=102,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,gridLeft=20,gridRight=20,gridTop=20,gridBottom=20,file="common/blank.png",
			{
				name="Image77",type=1,typeName="Image",time=0,x=0,y=0,width=84,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="lobby/welfareCenter.png"
			}
		},
		{
			name="friendScrollView",type=0,typeName="ScrollView",time=0,x=97,y=155,width=1,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight
		}
	},
	{
		name="broadcastView",type=0,typeName="View",time=0,x=0,y=117,width=720,height=64,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
		{
			name="view_speaker",type=0,typeName="View",time=0,x=92,y=0,width=580,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
			{
				name="view_content",type=0,typeName="View",time=0,x=0,y=0,width=580,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
			}
		},
		{
			name="btn_boradcast",type=1,typeName="Button",time=0,x=0,y=0,width=720,height=64,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="ui/blank.png"
		},
		{
			name="Image48",type=1,typeName="Image",time=0,x=43,y=3,width=40,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="lobby/hall_laba_icon.png"
		},
		{
			name="img_speakerLight",type=1,typeName="Image",time=0,x=4,y=-24,width=117,height=115,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="lobby/speaker_light.png"
		},
		{
			name="Image78",type=1,typeName="Image",time=0,x=39,y=63,width=641,height=2,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="lobby/underline.png"
		}
	},
	{
		name="moreView",type=1,typeName="Image",time=0,x=34,y=95,width=235,height=120,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,file="lobby/more_bg.png",
		{
			name="btn_setting",type=1,typeName="Button",time=0,x=98,y=-7,width=55,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="ui/blank.png",
			{
				name="Image75",type=1,typeName="Image",time=0,x=0,y=0,width=84,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="lobby/setting.png"
			}
		}
	}
}
return lobbyLayout;