local speakerPopu=
{
	name="speakerPopu",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="img_bgPanel",type=1,typeName="Image",time=0,x=0,y=0,width=720,height=568,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/v210/bg_middle.png",
		{
			name="btn_close",type=1,typeName="Button",time=0,x=307,y=-40,width=113,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/v210/closebtn_ .png"
		},
		{
			name="vb_mainTab",type=0,typeName="View",time=0,x=0,y=72,width=628,height=78,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,
			{
				name="img_bgMainTab",type=1,typeName="Image",time=0,x=0,y=0,width=620,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/tab_bg.png",gridLeft=40,gridRight=40,
				{
					name="img_tabSelHili",type=1,typeName="Image",time=0,x=-154,y=0,width=296,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/tab_select.png",gridLeft=40,gridRight=40
				},
				{
					name="btn_tabIdx1",type=1,typeName="Button",time=0,x=0,y=0,width=318,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="common/blank.png",
					{
						name="img_dscTabSel",type=1,typeName="Image",time=0,x=0,y=0,width=130,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="language/thai/popu/suona/suona_dscTabBtn1_sel.png"
					},
					{
						name="img_dscTabUnsel",type=1,typeName="Image",time=0,x=0,y=0,width=126,height=34,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="language/thai/popu/suona/suona_dscTabBtn1_unSel.png"
					}
				},
				{
					name="btn_tabIdx2",type=1,typeName="Button",time=0,x=0,y=0,width=318,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="common/blank.png",
					{
						name="img_dscTabSel",type=1,typeName="Image",time=0,x=0,y=0,width=172,height=36,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="language/thai/popu/suona/suona_dscTabBtn2_sel.png"
					},
					{
						name="img_dscTabUnsel",type=1,typeName="Image",time=0,x=0,y=0,width=168,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="language/thai/popu/suona/suona_dscTabBtn2_unSel.png"
					}
				}
			}
		},
		{
			name="vb_mainContPage",type=0,typeName="View",time=0,x=0,y=45,width=648,height=370,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,
			{
				name="vb_pageIdx1",type=0,typeName="View",time=0,x=0,y=0,width=648,height=370,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,
				{
					name="img_bgSuonaMsgInput",type=1,typeName="Image",time=0,x=0,y=0,width=628,height=184,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="common/img_inner_2.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20,
					{
						name="etv_suonaMsgCont",type=7,typeName="EditTextView",time=0,x=0,y=0,width=610,height=172,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignTopLeft,colorRed=255,colorGreen=255,colorBlue=255,colorA=1
					}
				},
				{
					name="tv_suonaUseTip",type=5,typeName="TextView",time=0,x=0,y=41,width=634,height=62,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=22,textAlign=kAlignTopLeft,colorRed=166,colorGreen=89,colorBlue=59,string=[[Suona Use Tip]],colorA=1
				},
				{
					name="btn_suonaSend",type=1,typeName="Button",time=0,x=0,y=18,width=250,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="popu/v210/btn_green.png",gridLeft=35,gridRight=35,gridTop=30,gridBottom=30,
					{
						name="img_dscSend",type=1,typeName="Image",time=0,x=0,y=-5,width=52,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="language/thai/popu/suona/suona_dscSend.png"
					},
					{
						name="img_bgSuonaCount",type=1,typeName="Image",time=0,x=-9,y=-8,width=44,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="popu/speaker/suona_bgSuonaCount.png",gridLeft=20,gridRight=23,gridTop=20,gridBottom=25,
						{
							name="txt_suonaCount",type=4,typeName="Text",time=0,x=0,y=-4,width=12,height=27,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[0]],colorA=1
						}
					}
				}
			},
			{
				name="vb_pageIdx2",type=0,typeName="View",time=0,x=0,y=0,width=648,height=370,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,
				{
					name="img_bgMsgRec",type=1,typeName="Image",time=0,x=0,y=0,width=626,height=320,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="common/img_inner_2.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20
				}
			}
		}
	}
}
return speakerPopu;