local shopPopu=
{
	name="shopPopu",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="img_popuBg",type=1,typeName="Image",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/bg_full.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20,
		{
			name="view_top",type=0,typeName="View",time=0,x=0,y=0,width=720,height=100,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
			{
				name="Image40",type=1,typeName="Image",time=0,x=0,y=60,width=720,height=82,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/shop/top_bg.png"
			},
			{
				name="topbarBg",type=1,typeName="Image",time=0,x=0,y=0,width=720,height=92,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="popu/topbar_2_bg.png"
			},
			{
				name="topCardView",type=0,typeName="View",time=0,x=5,y=15,width=244,height=59,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,
				{
					name="Image34",type=1,typeName="Image",time=0,x=0,y=0,width=244,height=59,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="7fdb8468c3809b5bcc67d79c64c6011e"
				},
				{
					name="Image35",type=1,typeName="Image",time=0,x=5,y=0,width=44,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="common/cash.png"
				},
				{
					name="addCardBtn",type=1,typeName="Button",time=0,x=0,y=0,width=77,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="56594e3d2cb8844871fb4368d10bc788"
				},
				{
					name="text_cardNum",type=4,typeName="Text",time=0,x=-8,y=0,width=95,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[520]],colorA=1
				}
			},
			{
				name="topChipView",type=0,typeName="View",time=0,x=254,y=15,width=284,height=59,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,
				{
					name="Image38",type=1,typeName="Image",time=0,x=0,y=0,width=284,height=59,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="7fdb8468c3809b5bcc67d79c64c6011e"
				},
				{
					name="Image39",type=1,typeName="Image",time=0,x=0,y=0,width=44,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="common/chip_1.png"
				},
				{
					name="text_chipNum",type=4,typeName="Text",time=0,x=0,y=0,width=100,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[9,999]]
				},
				{
					name="addChipBtn",type=1,typeName="Button",time=0,x=0,y=0,width=77,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="56594e3d2cb8844871fb4368d10bc788"
				}
			},
			{
				name="btn_back",type=1,typeName="Button",time=0,x=10,y=15,width=63,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="popu/btn_back.png"
			}
		},
		{
			name="img_titleBg",type=1,typeName="Image",time=0,x=0,y=155,width=680,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/tab_bg.png",gridLeft=40,gridRight=40,
			{
				name="btn_chip",type=1,typeName="Button",time=0,x=0,y=0,width=160,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="ui/blank.png",
				{
					name="Image33",type=1,typeName="Image",time=0,x=0,y=0,width=46,height=28,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyChip2.png"
				},
				{
					name="img_select",type=1,typeName="Image",time=0,x=0,y=0,width=160,height=62,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/tab_select.png",gridLeft=40,gridRight=40,
					{
						name="Image34",type=1,typeName="Image",time=0,x=0,y=0,width=56,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyChip1.png"
					}
				}
			},
			{
				name="btn_prop",type=1,typeName="Button",time=0,x=175,y=0,width=160,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="ui/blank.png",
				{
					name="Image35",type=1,typeName="Image",time=0,x=0,y=0,width=138,height=28,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/prop2.png"
				},
				{
					name="img_select",type=1,typeName="Image",time=0,x=0,y=0,width=150,height=62,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/tab_select.png",gridLeft=40,gridRight=40,
					{
						name="Image36",type=1,typeName="Image",time=0,x=0,y=0,width=148,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/prop1.png"
					}
				}
			},
			{
				name="btn_cash",type=1,typeName="Button",time=0,x=345,y=0,width=160,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="ui/blank.png",
				{
					name="Image37",type=1,typeName="Image",time=0,x=0,y=0,width=94,height=28,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyRoomCard2.png"
				},
				{
					name="img_select",type=1,typeName="Image",time=0,x=0,y=0,width=160,height=62,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/tab_select.png",gridLeft=40,gridRight=40,
					{
						name="Image38",type=1,typeName="Image",time=0,x=0,y=0,width=104,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyRoomCard1.png"
					}
				}
			},
			{
				name="btn_record",type=1,typeName="Button",time=0,x=520,y=0,width=160,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="ui/blank.png",
				{
					name="Image37",type=1,typeName="Image",time=0,x=0,y=0,width=134,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyRecord2.png"
				},
				{
					name="img_select",type=1,typeName="Image",time=0,x=0,y=0,width=160,height=62,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/tab_select.png",gridLeft=40,gridRight=40,
					{
						name="Image38",type=1,typeName="Image",time=0,x=0,y=0,width=142,height=44,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyRecord1.png"
					}
				}
			}
		},
		{
			name="Image38",type=1,typeName="Image",time=0,x=0,y=0,width=720,height=1040,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="popu/shop/floor_bg.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=10
		},
		{
			name="view_chip",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1035,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom
		},
		{
			name="view_prop",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1035,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom
		},
		{
			name="view_cash",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1035,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom
		},
		{
			name="view_record",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1035,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,
			{
				name="view_list",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1035,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
			},
			{
				name="text_record_empty",type=5,typeName="TextView",time=0,x=0,y=200,width=720,height=500,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=28,textAlign=kAlignTop,colorRed=203,colorGreen=221,colorBlue=239,string=[[TextView]],colorA=1
			}
		}
	}
}
return shopPopu;