local friendsPopu=
{
	name="friendsPopu",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,stageH=0,
	{
		name="img_popuBg",type=1,typeName="Image",time=0,x=0,y=0,width=720,height=1051,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/bigFrame.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20,
		{
			name="img_title",type=1,typeName="Image",time=0,x=0,y=-6,width=527,height=74,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/img_title_2.png",
			{
				name="Image19",type=1,typeName="Image",time=0,x=0,y=-5,width=96,height=52,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/friends/title.png"
			}
		},
		{
			name="btn_close",type=1,typeName="Button",time=0,x=607,y=-23,width=113,height=110,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="popu/closebtn_ .png"
		},
		{
			name="view_btnTab",type=0,typeName="View",time=0,x=0,y=90,width=626,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,
			{
				name="tab_bg",type=1,typeName="Image",time=0,x=0,y=0,width=626,height=74,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/tab_bg.png",gridLeft=40,gridRight=40
			},
			{
				name="img_tabSelect",type=0,typeName="View",time=0,x=0,y=0,width=313,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,
				{
					name="img_tabSelect2",type=1,typeName="Image",time=0,x=0,y=2,width=308,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/tab_select.png",gridLeft=40,gridRight=40
				}
			},
			{
				name="btn_friendList",type=1,typeName="Button",time=0,x=-156,y=0,width=313,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="ui/blank.png",
				{
					name="img_normal",type=1,typeName="Image",time=0,x=0,y=0,width=188,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/friends/tab_friend_list_1.png"
				},
				{
					name="img_select",type=1,typeName="Image",time=0,x=0,y=0,width=188,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/friends/tab_friend_list_2.png"
				}
			},
			{
				name="btn_addFriend",type=1,typeName="Button",time=0,x=156,y=0,width=313,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="ui/blank.png",
				{
					name="img_normal",type=1,typeName="Image",time=0,x=0,y=0,width=132,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/friends/tab_friend_add_1.png"
				},
				{
					name="img_select",type=1,typeName="Image",time=0,x=0,y=0,width=132,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/friends/tab_friend_add_2.png"
				}
			}
		},
		{
			name="Image14",type=1,typeName="Image",time=0,x=0,y=190,width=626,height=662,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="common/img_inner_2.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20
		},
		{
			name="view_sub",type=0,typeName="View",time=0,x=0,y=190,width=626,height=660,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,
			{
				name="view_friend_list",type=0,typeName="View",time=0,x=0,y=0,width=626,height=660,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
			},
			{
				name="view_friend_add",type=0,typeName="View",time=0,x=0,y=0,width=626,height=660,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft
			}
		},
		{
			name="Image22",type=1,typeName="Image",time=0,x=0,y=821,width=624,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="common/img_inner_2_shadow.png"
		},
		{
			name="btn_invite_more",type=1,typeName="Button",time=0,x=0,y=886,width=262,height=91,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="common/btn_yellow_big.png",
			{
				name="Image24",type=1,typeName="Image",time=0,x=0,y=-10,width=168,height=54,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/friends/invite_more.png"
			}
		}
	}
}
return friendsPopu;