local friendReqItem=
{
	name="friendReqItem",type=0,typeName="View",time=0,x=0,y=0,width=626,height=116,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
	{
		name="item_bg",type=1,typeName="Image",time=0,x=0,y=0,width=626,height=112,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="common/blank.png",
		{
			name="avatar_bg",type=1,typeName="Image",time=0,x=26,y=0,width=88,height=88,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="common/white.png"
		},
		{
			name="text_name",type=4,typeName="Text",time=0,x=130,y=-20,width=100,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=30,textAlign=kAlignLeft,colorRed=141,colorGreen=50,colorBlue=24,string=[[Text]],colorA=1
		},
		{
			name="Image7",type=1,typeName="Image",time=0,x=133,y=20,width=26,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="popu/friends/tag_chip.png"
		},
		{
			name="text_chip",type=4,typeName="Text",time=0,x=175,y=20,width=100,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignLeft,colorRed=244,colorGreen=254,colorBlue=4,string=[[55214]],colorA=1
		},
		{
			name="sex",type=1,typeName="Image",time=0,x=240,y=-20,width=22,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="popu/friends/male.png"
		},
		{
			name="btn_ok",type=1,typeName="Button",time=0,x=26,y=0,width=146,height=74,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="common/btn_green_min.png",
			{
				name="Image12",type=1,typeName="Image",time=0,x=0,y=-5,width=98,height=34,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/friends/accept.png"
			}
		},
		{
			name="btn_refuse",type=1,typeName="Button",time=0,x=180,y=0,width=146,height=72,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="common/btn_blue_min.png",
			{
				name="Image11",type=1,typeName="Image",time=0,x=0,y=-3,width=90,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/friends/refuse.png"
			}
		}
	},
	{
		name="line",type=1,typeName="Image",time=0,x=0,y=0,width=624,height=4,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="popu/friends/separate_lines.png"
	}
}
return friendReqItem;