local view_player=
{
	name="view_player",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,stageW=0,
	{
		name="btn_player",type=1,typeName="Button",time=0,x=0,y=0,width=124,height=124,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="common/blank.png",
		{
			name="img_headbg",type=1,typeName="Image",time=0,x=0,y=0,width=124,height=124,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="games/common/img_headBg.png",
			{
				name="img_sitdown",type=1,typeName="Image",time=0,x=0,y=0,width=51,height=45,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="games/common/img_sitdown.png"
			},
			{
				name="view_phead",type=0,typeName="View",time=0,x=0,y=0,width=124,height=124,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft
			},
			{
				name="view_progress",type=0,typeName="View",time=0,x=0,y=0,width=124,height=124,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft
			}
		},
		{
			name="img_chipbg",type=1,typeName="Image",time=0,x=0,y=-25,width=163,height=54,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="games/common/img_headInfo_bg.png",
			{
				name="text_name",type=4,typeName="Text",time=0,x=0,y=0,width=71.55,height=27.15,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=24,textAlign=kAlignTop,colorRed=255,colorGreen=255,colorBlue=255,string=[[Abbott]],colorA=1
			},
			{
				name="text_chip",type=4,typeName="Text",time=0,x=0,y=0,width=95.7,height=27.15,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=24,textAlign=kAlignTop,colorRed=222,colorGreen=163,colorBlue=22,string=[[$898,612]],colorA=1
			}
		},
		{
			name="btn_gift",type=1,typeName="Button",time=0,x=0,y=0,width=41,height=41,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="common/blank.png",
			{
				name="img_gift",type=1,typeName="Image",time=0,x=0,y=0,width=41,height=41,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="games/common/img_gift.png"
			}
		},
		{
			name="view_waitingNext",type=0,typeName="View",time=0,x=0,y=0,width=124,height=124,visible=0,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,
			{
				name="Image13",type=1,typeName="Image",time=0,x=0,y=0,width=124,height=124,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,file="games/common/head_mask.png",alphaValue=0.4
			},
			{
				name="text_waitingNext",type=4,typeName="Text",time=0,x=0,y=0,width=160,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[等待下一局]]
			}
		}
	}
}
return view_player;