local shopPopu=
{
	name="shopPopu",type=0,typeName="View",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="img_popuBg",type=1,typeName="Image",time=0,x=0,y=0,width=720,height=1280,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/bg_full.png",gridLeft=20,gridRight=20,gridTop=20,gridBottom=20,
		{
			name="view_top",type=0,typeName="View",time=0,x=0,y=0,width=720,height=81,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,
			{
				name="Image40",type=1,typeName="Image",time=0,x=0,y=60,width=720,height=82,visible=0,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/shop/top_bg.png"
			},
			{
				name="topbarBg",type=1,typeName="Image",time=0,x=0,y=0,width=720,height=81,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="popu/topbar_2_bg.png"
			},
			{
				name="topCardView",type=0,typeName="View",time=0,x=15,y=0,width=198,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,
				{
					name="Image34",type=1,typeName="Image",time=0,x=0,y=0,width=198,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="popu/chip_bg.png",gridRight=22
				},
				{
					name="Image35",type=1,typeName="Image",time=0,x=-35,y=0,width=70,height=68,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="lobby/hall_cash.png"
				},
				{
					name="addCardBtn",type=1,typeName="Button",time=0,x=0,y=0,width=233,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="common/blank.png"
				},
				{
					name="text_cardNum",type=4,typeName="Text",time=0,x=0,y=0,width=120,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[520]],colorA=1
				}
			},
			{
				name="topChipView",type=0,typeName="View",time=0,x=260,y=0,width=216,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,
				{
					name="Image38",type=1,typeName="Image",time=0,x=0,y=0,width=216,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="popu/chip_bg.png",gridRight=22
				},
				{
					name="Image39",type=1,typeName="Image",time=0,x=-35,y=0,width=70,height=68,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="lobby/hall_chip.png"
				},
				{
					name="text_chipNum",type=4,typeName="Text",time=0,x=0,y=0,width=150,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[9,999]]
				},
				{
					name="addChipBtn",type=1,typeName="Button",time=0,x=0,y=0,width=251,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="common/blank.png"
				}
			},
			{
				name="btn_back",type=1,typeName="Button",time=0,x=15,y=0,width=70,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="popu/btn_back.png"
			}
		},
		{
			name="Image43",type=1,typeName="Image",time=0,x=0,y=0,width=712,height=1075,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="popu/shop/shop_bg.png",gridLeft=21,gridRight=21,gridTop=23,gridBottom=23
		},
		{
			name="view_chip",type=0,typeName="View",time=0,x=0,y=0,width=720,height=947,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom
		},
		{
			name="view_prop",type=0,typeName="View",time=0,x=0,y=0,width=720,height=947,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom
		},
		{
			name="view_cash",type=0,typeName="View",time=0,x=0,y=0,width=720,height=947,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom
		},
		{
			name="view_record",type=0,typeName="View",time=0,x=0,y=0,width=720,height=947,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,
			{
				name="view_list",type=0,typeName="View",time=0,x=0,y=0,width=700,height=936,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop
			},
			{
				name="text_record_empty",type=5,typeName="TextView",time=0,x=0,y=200,width=720,height=500,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=28,textAlign=kAlignTop,colorRed=77,colorGreen=77,colorBlue=77,string=[[TextView]],colorA=1
			}
		},
		{
			name="img_titleBg",type=1,typeName="Image",time=0,x=0,y=255,width=690,height=78,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/shop/tab_bg.png",gridLeft=41,gridRight=41,
			{
				name="btn_chip",type=1,typeName="Button",time=0,x=-255,y=0,width=170,height=78,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="ui/blank.png",
				{
					name="Image33",type=1,typeName="Image",time=0,x=0,y=-1,width=111,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyChip2.png"
				},
				{
					name="img_select",type=1,typeName="Image",time=0,x=0,y=1,width=168,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/tab_select.png",gridLeft=40,gridRight=40,
					{
						name="Image34",type=1,typeName="Image",time=0,x=0,y=-2,width=111,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyChip1.png"
					}
				}
			},
			{
				name="btn_prop",type=1,typeName="Button",time=0,x=-85,y=0,width=170,height=78,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="ui/blank.png",
				{
					name="Image35",type=1,typeName="Image",time=0,x=0,y=-1,width=111,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/prop2.png"
				},
				{
					name="img_select",type=1,typeName="Image",time=0,x=0,y=1,width=168,height=64,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/tab_select.png",gridLeft=40,gridRight=40,
					{
						name="Image36",type=1,typeName="Image",time=0,x=0,y=-2,width=111,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/prop1.png"
					}
				}
			},
			{
				name="btn_cash",type=1,typeName="Button",time=0,x=85,y=0,width=170,height=78,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="ui/blank.png",
				{
					name="Image37",type=1,typeName="Image",time=0,x=0,y=-5,width=111,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyRoomCard2.png"
				},
				{
					name="img_select",type=1,typeName="Image",time=0,x=0,y=1,width=168,height=64,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/tab_select.png",gridLeft=40,gridRight=40,
					{
						name="Image38",type=1,typeName="Image",time=0,x=0,y=-6,width=111,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyRoomCard1.png"
					}
				}
			},
			{
				name="btn_record",type=1,typeName="Button",time=0,x=255,y=0,width=170,height=78,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="ui/blank.png",
				{
					name="Image37",type=1,typeName="Image",time=0,x=0,y=-4,width=111,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyRecord2.png"
				},
				{
					name="img_select",type=1,typeName="Image",time=0,x=0,y=1,width=168,height=64,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/tab_select.png",gridLeft=40,gridRight=40,
					{
						name="Image38",type=1,typeName="Image",time=0,x=0,y=-5,width=111,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="popu/shop/text/buyRecord1.png"
					}
				}
			}
		},
		{
			name="Image41",type=1,typeName="Image",time=0,x=0,y=90,width=720,height=170,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="popu/shop/canopy.png"
		},
		{
			name="Image42",type=1,typeName="Image",time=0,x=0,y=95,width=348,height=130,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="popu/shop/title.png"
		}
	}
}
return shopPopu;